name: App 1

on:
  pull_request:
    paths:
    - app1/**
    - .github/workflows/app1.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        cd app1
    - name: Run tests
      env:
        CI: true
      run: npm run test
